# Copyright (c) 2026 The Dash Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/license/mit/.

# Match libdashkernel_la_SOURCES in src/Makefile.am. The kernel supplies its
# own globals and helpers instead of pulling in the full node and RPC layers.
add_library(bitcoinkernel STATIC EXCLUDE_FROM_ALL
  bitcoinkernel.cpp
  ../arith_uint256.cpp
  ../base58.cpp
  ../batchedlogger.cpp
  ../bech32.cpp
  ../blockfilter.cpp
  ../bls/bls.cpp
  ../bls/bls_worker.cpp
  ../chain.cpp
  ../chainlock/chainlock.cpp
  ../chainlock/clsig.cpp
  ../chainparams.cpp
  ../chainparamsbase.cpp
  ../coins.cpp
  ../common/bloom.cpp
  ../compressor.cpp
  ../consensus/merkle.cpp
  ../consensus/tx_check.cpp
  ../consensus/tx_verify.cpp
  ../core_read.cpp
  ../dbwrapper.cpp
  ../deploymentinfo.cpp
  ../deploymentstatus.cpp
  ../evo/assetlocktx.cpp
  ../evo/cbtx.cpp
  ../evo/chainhelper.cpp
  ../evo/creditpool.cpp
  ../evo/deterministicmns.cpp
  ../evo/dmnstate.cpp
  ../evo/evodb.cpp
  ../evo/mnhftx.cpp
  ../evo/netinfo.cpp
  ../evo/providertx.cpp
  ../evo/providertx_util.cpp
  ../evo/simplifiedmns.cpp
  ../evo/smldiff.cpp
  ../evo/specialtx.cpp
  ../evo/specialtx_filter.cpp
  ../evo/specialtxman.cpp
  ../flatfile.cpp
  ../governance/common.cpp
  ../governance/object.cpp
  ../governance/superblock.cpp
  ../governance/vote.cpp
  ../governance/votedb.cpp
  ../gsl/assert.cpp
  ../hash.cpp
  ../index/addressindex.cpp
  ../index/addressindex_util.cpp
  ../index/base.cpp
  ../index/blockfilterindex.cpp
  ../index/coinstatsindex.cpp
  ../index/spentindex.cpp
  ../index/txindex.cpp
  ../init/common.cpp
  ../instantsend/db.cpp
  ../instantsend/instantsend.cpp
  chain.cpp
  checks.cpp
  coinstats.cpp
  context.cpp
  mempool_persist.cpp
  ../key.cpp
  ../key_io.cpp
  ../llmq/blockprocessor.cpp
  ../llmq/commitment.cpp
  ../llmq/context.cpp
  ../llmq/debug.cpp
  ../llmq/dkgsession.cpp
  ../llmq/dkgsessionhandler.cpp
  ../llmq/dkgsessionmgr.cpp
  ../llmq/options.cpp
  ../llmq/quorums.cpp
  ../llmq/quorumsman.cpp
  ../llmq/signhash.cpp
  ../llmq/signing.cpp
  ../llmq/snapshot.cpp
  ../llmq/utils.cpp
  ../logging.cpp
  ../masternode/meta.cpp
  ../masternode/payments.cpp
  ../masternode/sync.cpp
  ../merkleblock.cpp
  ../messagesigner.cpp
  ../netaddress.cpp
  ../netbase.cpp
  ../node/blockstorage.cpp
  ../node/chainstate.cpp
  ../node/interface_ui.cpp
  ../node/transaction.cpp
  ../node/utxo_snapshot.cpp
  ../policy/feerate.cpp
  ../policy/fees.cpp
  ../policy/packages.cpp
  ../policy/policy.cpp
  ../policy/settings.cpp
  ../pow.cpp
  ../primitives/block.cpp
  ../primitives/transaction.cpp
  ../protocol.cpp
  ../pubkey.cpp
  ../random.cpp
  ../randomenv.cpp
  ../saltedhasher.cpp
  ../scheduler.cpp
  ../script/interpreter.cpp
  ../script/script.cpp
  ../script/script_error.cpp
  ../script/sigcache.cpp
  ../script/standard.cpp
  ../shutdown.cpp
  ../spork.cpp
  ../support/cleanse.cpp
  ../support/lockedpool.cpp
  ../sync.cpp
  ../timedata.cpp
  ../txdb.cpp
  ../txmempool.cpp
  ../uint256.cpp
  ../util/bytevectorhash.cpp
  ../util/check.cpp
  ../util/fs.cpp
  ../util/fs_helpers.cpp
  ../util/getuniquepath.cpp
  ../util/hasher.cpp
  ../util/message.cpp
  ../util/moneystr.cpp
  ../util/ranges_set.cpp
  ../util/serfloat.cpp
  ../util/settings.cpp
  ../util/sock.cpp
  ../util/strencodings.cpp
  ../util/string.cpp
  ../util/syserror.cpp
  ../util/system.cpp
  ../util/thread.cpp
  ../util/threadinterrupt.cpp
  ../util/threadnames.cpp
  ../util/time.cpp
  ../util/tokenpipe.cpp
  ../validation.cpp
  ../validationinterface.cpp
  ../versionbits.cpp
  ../warnings.cpp
  $<TARGET_OBJECTS:bitcoin_clientversion>
)
target_compile_definitions(bitcoinkernel PRIVATE BUILD_BITCOIN_INTERNAL)
target_link_libraries(bitcoinkernel
  PRIVATE
    core_interface
    bitcoin_crypto
    $<TARGET_NAME_IF_EXISTS:USDT::headers>
    $<$<PLATFORM_ID:Windows>:ws2_32>
  PUBLIC
    Boost::headers
    dashbls
    leveldb
    univalue
    secp256k1
)
