// Copyright (c) 2026 The Dash Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <platform/dpp/document.h>
#include <platform/dpp/identity.h>
#include <platform/statetransitions.h>

#include <crypto/sha256.h>
#include <hash.h>
#include <key.h>
#include <test/util/setup_common.h>
#include <uint256.h>
#include <util/strencodings.h>

#include <test/data/platform/dpp_identity_vectors.json.h>
#include <test/data/platform/dpp_st_vectors.json.h>

#include <boost/test/unit_test.hpp>

#include <univalue.h>

#include <array>
#include <string>
#include <vector>

/**
 * Byte-exactness tests for src/platform/dpp/ against vectors generated by
 * the real rs-dpp (dashpay/platform tag v4.0.0, protocol version 12) via
 * the platform-dpp-vectors crate
 * (github.com/PastaPastaPasta/dash-platform-test-vectors).
 */

using namespace platform;

BOOST_FIXTURE_TEST_SUITE(platform_dpp_tests, BasicTestingSetup)

namespace {

UniValue LoadVectors(const unsigned char* data, size_t size)
{
    // Not read_json(): these vector files are JSON objects, not arrays.
    UniValue vectors;
    BOOST_REQUIRE(vectors.read(std::string(data, data + size)));
    BOOST_REQUIRE(vectors.isObject());
    return vectors;
}

std::vector<uint8_t> FromHex(const std::string& hex)
{
    BOOST_REQUIRE(IsHex(hex));
    return ParseHex(hex);
}

template <size_t N>
std::array<uint8_t, N> ArrayFromHex(const std::string& hex)
{
    const std::vector<uint8_t> bytes{FromHex(hex)};
    BOOST_REQUIRE_EQUAL(bytes.size(), N);
    std::array<uint8_t, N> out;
    std::copy(bytes.begin(), bytes.end(), out.begin());
    return out;
}

//! Deterministic signer over a fixed private key: RFC6979 compact
//! recoverable signature, exactly what interfaces::Wallet::signPlatformDigest
//! produces and what the vectors were signed with (dashcore::signer).
st::Signer MakeSigner(const std::string& privkey_hex, const uint256* expected_digest = nullptr)
{
    const std::vector<uint8_t> priv{FromHex(privkey_hex)};
    return [priv, expected_digest](const uint256& digest, std::vector<uint8_t>& sig_out) {
        if (expected_digest != nullptr) BOOST_CHECK_EQUAL(digest, *expected_digest);
        CKey key;
        key.Set(priv.begin(), priv.end(), /*fCompressedIn=*/true);
        if (!key.IsValid()) return false;
        return key.SignCompact(digest, sig_out);
    };
}

void CheckBuilt(const st::Result<st::BuiltTransition>& result, const UniValue& vec)
{
    BOOST_REQUIRE_MESSAGE(result.ok(), result.error);
    const std::vector<uint8_t> expected{FromHex(vec["serialized_hex"].get_str())};
    BOOST_CHECK_EQUAL(HexStr(result.value->bytes), HexStr(expected));
    // The wait handle is the single SHA256 of the serialized transition
    // (rs-dpp StateTransition::transaction_id).
    uint256 expected_hash;
    CSHA256().Write(expected.data(), expected.size()).Finalize(expected_hash.begin());
    BOOST_CHECK_EQUAL(result.value->hash, expected_hash);
}

uint256 DigestOf(const UniValue& vec)
{
    return uint256{FromHex(vec["digest_hex"].get_str())};
}

//! Document id: DSHA256(contract_id || owner_id || type_name || entropy),
//! per rs-dpp Document::generate_document_id_v0. Local mirror used to check
//! the document ids the bridge-built transitions must carry.
Identifier GenerateDocumentId(const Identifier& contract_id, const Identifier& owner_id,
                              const std::string& document_type_name, Span<const uint8_t> entropy)
{
    CHash256 hasher;
    hasher.Write(contract_id);
    hasher.Write(owner_id);
    hasher.Write(MakeUCharSpan(document_type_name));
    hasher.Write(entropy);
    uint256 hash;
    hasher.Finalize(hash);
    Identifier ret;
    std::copy(hash.begin(), hash.end(), ret.begin());
    return ret;
}

} // namespace

BOOST_AUTO_TEST_CASE(identity_decode)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_identity_vectors, sizeof(json_tests::dpp_identity_vectors))};
    const UniValue& id_vec{vectors["identity"]};
    const std::vector<uint8_t> bytes{FromHex(id_vec["serialized_hex"].get_str())};

    std::string error;
    const auto identity{dpp::DecodeIdentity(bytes, error)};
    BOOST_REQUIRE_MESSAGE(identity.has_value(), error);
    BOOST_CHECK_EQUAL(HexStr(identity->id), id_vec["id"].get_str());
    BOOST_CHECK_EQUAL(identity->balance, id_vec["balance"].getInt<uint64_t>());
    BOOST_CHECK_EQUAL(identity->revision, id_vec["revision"].getInt<uint64_t>());

    const UniValue& keys{id_vec["public_keys"]};
    BOOST_REQUIRE_EQUAL(identity->public_keys.size(), keys.size());
    for (size_t i = 0; i < keys.size(); ++i) {
        const UniValue& expected{keys[i]};
        const IdentityPublicKey& key{identity->public_keys[i]};
        BOOST_CHECK_EQUAL(key.id, expected["id"].getInt<uint32_t>());
        BOOST_CHECK_EQUAL(static_cast<int>(key.purpose), expected["purpose"].getInt<int>());
        BOOST_CHECK_EQUAL(static_cast<int>(key.security_level), expected["security_level"].getInt<int>());
        BOOST_CHECK_EQUAL(static_cast<int>(key.type), expected["key_type"].getInt<int>());
        BOOST_CHECK_EQUAL(key.read_only, expected["read_only"].get_bool());
        BOOST_CHECK_EQUAL(HexStr(key.data), expected["data"].get_str());
        if (expected["disabled_at"].isNull()) {
            BOOST_CHECK(!key.disabled_at.has_value());
        } else {
            BOOST_REQUIRE(key.disabled_at.has_value());
            BOOST_CHECK_EQUAL(*key.disabled_at, expected["disabled_at"].getInt<uint64_t>());
        }
    }

    // Negative: truncation and unknown versions fail. (Trailing bytes are
    // tolerated: rs-dpp's deserializer, like the Rust SDK, ignores unread
    // input past a complete object.)
    for (size_t len : {size_t{0}, size_t{1}, size_t{16}, bytes.size() - 1}) {
        std::string err;
        BOOST_CHECK(!dpp::DecodeIdentity(Span{bytes}.first(len), err));
        BOOST_CHECK(!err.empty());
    }
    {
        std::vector<uint8_t> bad_version{bytes};
        bad_version[0] = 0x01;
        std::string err;
        BOOST_CHECK(!dpp::DecodeIdentity(bad_version, err));
    }
    {
        // Corrupt the key count so the map runs off the end of the buffer.
        std::vector<uint8_t> bad_count{bytes};
        bad_count[33] = 0x63; // 99 keys
        std::string err;
        BOOST_CHECK(!dpp::DecodeIdentity(bad_count, err));
    }
}

BOOST_AUTO_TEST_CASE(identity_public_key_decode)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_identity_vectors, sizeof(json_tests::dpp_identity_vectors))};
    const UniValue& key_vec{vectors["identity_public_key"]};
    const std::vector<uint8_t> bytes{FromHex(key_vec["serialized_hex"].get_str())};
    const UniValue& fields{key_vec["fields"]};

    std::string error;
    const auto key{dpp::DecodeIdentityPublicKey(bytes, error)};
    BOOST_REQUIRE_MESSAGE(key.has_value(), error);
    BOOST_CHECK_EQUAL(key->id, fields["id"].getInt<uint32_t>());
    BOOST_CHECK_EQUAL(static_cast<int>(key->purpose), fields["purpose"].getInt<int>());
    BOOST_CHECK_EQUAL(static_cast<int>(key->security_level), fields["security_level"].getInt<int>());
    BOOST_CHECK_EQUAL(static_cast<int>(key->type), fields["key_type"].getInt<int>());
    BOOST_CHECK_EQUAL(HexStr(key->data), fields["data"].get_str());

    std::string err;
    BOOST_CHECK(!dpp::DecodeIdentityPublicKey(Span{bytes}.first(bytes.size() - 1), err));
}

BOOST_AUTO_TEST_CASE(identity_create)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const UniValue& keys{vectors["keys"]};

    std::vector<st::NewIdentityKey> new_keys;
    {
        st::NewIdentityKey master;
        master.id = 0;
        master.purpose = IdentityPublicKey::Purpose::AUTHENTICATION;
        master.security_level = IdentityPublicKey::SecurityLevel::MASTER;
        master.pubkey = FromHex(keys["master"]["public_key_hex"].get_str());
        master.signer = MakeSigner(keys["master"]["private_key_hex"].get_str());
        st::NewIdentityKey high;
        high.id = 1;
        high.purpose = IdentityPublicKey::Purpose::AUTHENTICATION;
        high.security_level = IdentityPublicKey::SecurityLevel::HIGH;
        high.pubkey = FromHex(keys["high"]["public_key_hex"].get_str());
        high.signer = MakeSigner(keys["high"]["private_key_hex"].get_str());
        // Deliberately unsorted: the builder must order keys by id.
        new_keys = {high, master};
    }
    const std::string asset_lock_priv{keys["asset_lock"]["private_key_hex"].get_str()};

    {
        const UniValue& vec{vectors["identity_create_instant"]};
        st::InstantAssetLockProof proof;
        proof.transaction = FromHex(vec["transaction_hex"].get_str());
        proof.instant_lock = FromHex(vec["instant_lock_hex"].get_str());
        proof.output_index = vec["output_index"].getInt<uint32_t>();

        const uint256 digest{DigestOf(vec)};
        const auto result{st::BuildIdentityCreate({proof}, new_keys, MakeSigner(asset_lock_priv, &digest))};
        CheckBuilt(result, vec);

        const auto out_point{ArrayFromHex<36>(vec["out_point_hex"].get_str())};
        BOOST_CHECK_EQUAL(HexStr(st::IdentityIdFromOutpoint(out_point)), vec["identity_id_hex"].get_str());
    }
    {
        const UniValue& vec{vectors["identity_create_chain"]};
        st::ChainAssetLockProof proof;
        proof.core_chain_locked_height = vec["core_chain_locked_height"].getInt<uint32_t>();
        proof.out_point = ArrayFromHex<36>(vec["out_point_hex"].get_str());

        const uint256 digest{DigestOf(vec)};
        const auto result{st::BuildIdentityCreate({proof}, new_keys, MakeSigner(asset_lock_priv, &digest))};
        CheckBuilt(result, vec);
        BOOST_CHECK_EQUAL(HexStr(st::IdentityIdFromOutpoint(proof.out_point)), vec["identity_id_hex"].get_str());
    }

    // Signer failure surfaces as an error, not a malformed transition.
    const auto failed{st::BuildIdentityCreate(
        {st::ChainAssetLockProof{}}, new_keys,
        [](const uint256&, std::vector<uint8_t>&) { return false; })};
    BOOST_CHECK(!failed.ok());
    BOOST_CHECK(!failed.error.empty());
}

BOOST_AUTO_TEST_CASE(dpns_preorder)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const UniValue& vec{vectors["dpns_preorder"]};
    const std::string high_priv{vectors["keys"]["high"]["private_key_hex"].get_str()};

    const auto owner{ArrayFromHex<32>(vec["owner_id_hex"].get_str())};
    const auto salt{ArrayFromHex<32>(vec["salt_hex"].get_str())};
    const std::string normalized{st::NormalizeLabel(vec["label"].get_str())};
    BOOST_CHECK_EQUAL(normalized, vec["normalized_label"].get_str());

    const auto salted_hash{st::SaltedDomainHash(salt, normalized, "dash")};
    BOOST_CHECK_EQUAL(HexStr(salted_hash), vec["salted_domain_hash_hex"].get_str());

    const uint256 digest{DigestOf(vec)};
    const auto result{st::BuildDpnsPreorder(owner, vec["identity_contract_nonce"].getInt<uint64_t>(),
                                            vec["label"].get_str(), salt,
                                            vec["signature_public_key_id"].getInt<uint32_t>(),
                                            MakeSigner(high_priv, &digest))};
    CheckBuilt(result, vec);

    // The preorder document id derives from the salted-domain-hash entropy
    // (the bridge recomputes the hash from label and salt).
    const auto doc_id{GenerateDocumentId(DPNS_CONTRACT_ID, owner, "preorder", salted_hash)};
    BOOST_CHECK_EQUAL(HexStr(doc_id), vec["document_id_hex"].get_str());
}

BOOST_AUTO_TEST_CASE(dpns_domain)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const std::string high_priv{vectors["keys"]["high"]["private_key_hex"].get_str()};

    for (const char* name : {"dpns_domain_contested", "dpns_domain"}) {
        const UniValue& vec{vectors[name]};
        const auto owner{ArrayFromHex<32>(vec["owner_id_hex"].get_str())};
        const auto salt{ArrayFromHex<32>(vec["salt_hex"].get_str())};
        const std::string label{vec["label"].get_str()};
        const std::string normalized{st::NormalizeLabel(label)};
        BOOST_CHECK_EQUAL(normalized, vec["normalized_label"].get_str());
        BOOST_CHECK_EQUAL(st::IsContestedLabel(normalized), vec["contested"].get_bool());

        const uint256 digest{DigestOf(vec)};
        const auto result{st::BuildDpnsDomain(owner, vec["identity_contract_nonce"].getInt<uint64_t>(),
                                              label, normalized, "dash", salt,
                                              vec["signature_public_key_id"].getInt<uint32_t>(),
                                              MakeSigner(high_priv, &digest))};
        CheckBuilt(result, vec);

        // The domain document id derives from the preorder-salt entropy.
        const auto doc_id{GenerateDocumentId(DPNS_CONTRACT_ID, owner, "domain", salt)};
        BOOST_CHECK_EQUAL(HexStr(doc_id), vec["document_id_hex"].get_str());
    }

    // A mismatched normalized label is rejected before signing.
    const auto owner{ArrayFromHex<32>(vectors["dpns_domain"]["owner_id_hex"].get_str())};
    const auto bad{st::BuildDpnsDomain(owner, 1, "Alice", "alice", "dash", {}, 1,
                                       MakeSigner(high_priv))};
    BOOST_CHECK(!bad.ok());
}

BOOST_AUTO_TEST_CASE(dashpay_profile)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const std::string high_priv{vectors["keys"]["high"]["private_key_hex"].get_str()};

    const UniValue& create_vec{vectors["dashpay_profile_create"]};
    const auto owner{ArrayFromHex<32>(create_vec["owner_id_hex"].get_str())};

    Profile profile;
    profile.display_name = create_vec["display_name"].get_str();
    profile.public_message = create_vec["public_message"].get_str();
    profile.avatar_url = create_vec["avatar_url"].get_str();
    profile.avatar_hash = FromHex(create_vec["avatar_hash_hex"].get_str());
    profile.avatar_fingerprint = FromHex(create_vec["avatar_fingerprint_hex"].get_str());

    {
        const uint256 digest{DigestOf(create_vec)};
        const auto result{st::BuildProfile(owner, create_vec["identity_contract_nonce"].getInt<uint64_t>(),
                                           profile, /*revision=*/1, std::nullopt,
                                           create_vec["signature_public_key_id"].getInt<uint32_t>(),
                                           MakeSigner(high_priv, &digest))};
        CheckBuilt(result, create_vec);
    }
    {
        const UniValue& replace_vec{vectors["dashpay_profile_replace"]};
        Profile updated{profile};
        updated.public_message = replace_vec["public_message"].get_str();
        const auto existing_id{ArrayFromHex<32>(replace_vec["document_id_hex"].get_str())};
        const uint256 digest{DigestOf(replace_vec)};
        const auto result{st::BuildProfile(owner, replace_vec["identity_contract_nonce"].getInt<uint64_t>(),
                                           updated, /*revision=*/2, existing_id,
                                           replace_vec["signature_public_key_id"].getInt<uint32_t>(),
                                           MakeSigner(high_priv, &digest))};
        CheckBuilt(result, replace_vec);
    }

    // Schema guards: malformed avatar metadata is rejected.
    Profile bad{profile};
    bad.avatar_hash.assign(31, 0x00);
    BOOST_CHECK(!st::BuildProfile(owner, 1, bad, 1, std::nullopt, 1, MakeSigner(high_priv)).ok());
}

BOOST_AUTO_TEST_CASE(dashpay_contact_request)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const UniValue& vec{vectors["dashpay_contact_request"]};
    const std::string high_priv{vectors["keys"]["high"]["private_key_hex"].get_str()};
    const auto owner{ArrayFromHex<32>(vec["owner_id_hex"].get_str())};

    ContactRequest request;
    request.to_user_id = ArrayFromHex<32>(vec["to_user_id_hex"].get_str());
    request.encrypted_public_key = FromHex(vec["encrypted_public_key_hex"].get_str());
    request.sender_key_index = vec["sender_key_index"].getInt<uint32_t>();
    request.recipient_key_index = vec["recipient_key_index"].getInt<uint32_t>();
    request.account_reference = vec["account_reference"].getInt<uint32_t>();
    request.encrypted_account_label = FromHex(vec["encrypted_account_label_hex"].get_str());

    const uint256 digest{DigestOf(vec)};
    const auto result{st::BuildContactRequest(owner, vec["identity_contract_nonce"].getInt<uint64_t>(),
                                              request, vec["signature_public_key_id"].getInt<uint32_t>(),
                                              MakeSigner(high_priv, &digest))};
    CheckBuilt(result, vec);

    ContactRequest bad{request};
    bad.encrypted_public_key.resize(95);
    BOOST_CHECK(!st::BuildContactRequest(owner, 1, bad, 1, MakeSigner(high_priv)).ok());
}

BOOST_AUTO_TEST_CASE(contested_labels)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const UniValue& cases{vectors["contested_labels"]};
    BOOST_REQUIRE(cases.isArray());
    for (size_t i = 0; i < cases.size(); ++i) {
        const UniValue& test{cases[i]};
        const std::string label{test["label"].get_str()};
        const std::string normalized{st::NormalizeLabel(label)};
        BOOST_CHECK_EQUAL(normalized, test["normalized"].get_str());
        BOOST_CHECK_MESSAGE(st::IsContestedLabel(normalized) == test["contested"].get_bool(),
                            "contested mismatch for label " + label);
    }
    // Port of the rs-dpp convert_to_homograph_safe_chars unit test input.
    BOOST_CHECK_EQUAL(st::NormalizeLabel("A0boic0Dlelfl"), "a0b01c0d1e1f1");
}

BOOST_AUTO_TEST_CASE(stored_document_decoders)
{
    const UniValue vectors{LoadVectors(json_tests::dpp_st_vectors, sizeof(json_tests::dpp_st_vectors))};
    const UniValue& stored{vectors["stored_documents"]};
    {
        const UniValue& expected{stored["domain"]};
        DpnsName domain;
        const auto bytes{FromHex(expected["serialized_hex"].get_str())};
        BOOST_REQUIRE(dpp::DecodeDpnsDomain(bytes, domain));
        BOOST_CHECK_EQUAL(HexStr(domain.document_id), expected["id_hex"].get_str());
        BOOST_CHECK_EQUAL(HexStr(domain.identity), expected["identity_id_hex"].get_str());
        BOOST_CHECK_EQUAL(domain.label, expected["label"].get_str());
        BOOST_CHECK_EQUAL(domain.normalized_label, expected["normalized_label"].get_str());
        BOOST_CHECK_EQUAL(domain.parent_domain, "dash");
    }
    {
        const UniValue& expected{stored["profile"]};
        Profile profile;
        const auto bytes{FromHex(expected["serialized_hex"].get_str())};
        BOOST_REQUIRE(dpp::DecodeDashPayProfile(bytes, profile));
        BOOST_CHECK_EQUAL(HexStr(profile.document_id), expected["id_hex"].get_str());
        BOOST_CHECK_EQUAL(HexStr(profile.owner_id), expected["owner_id_hex"].get_str());
        BOOST_CHECK_EQUAL(profile.revision, expected["revision"].getInt<uint64_t>());
        BOOST_CHECK_EQUAL(profile.display_name, expected["display_name"].get_str());
        BOOST_CHECK_EQUAL(profile.public_message, expected["public_message"].get_str());
        BOOST_CHECK_EQUAL(profile.avatar_url, expected["avatar_url"].get_str());
        BOOST_CHECK_EQUAL(profile.created_at, expected["created_at"].getInt<uint64_t>());
        BOOST_CHECK_EQUAL(profile.updated_at, expected["updated_at"].getInt<uint64_t>());
    }
    {
        const UniValue& expected{stored["contact"]};
        ContactRequest contact;
        const auto bytes{FromHex(expected["serialized_hex"].get_str())};
        BOOST_REQUIRE(dpp::DecodeDashPayContactRequest(bytes, contact));
        BOOST_CHECK_EQUAL(HexStr(contact.document_id), expected["id_hex"].get_str());
        BOOST_CHECK_EQUAL(HexStr(contact.owner_id), expected["owner_id_hex"].get_str());
        BOOST_CHECK_EQUAL(HexStr(contact.to_user_id), expected["to_user_id_hex"].get_str());
        BOOST_CHECK_EQUAL(contact.sender_key_index, expected["sender_key_index"].getInt<uint32_t>());
        BOOST_CHECK_EQUAL(contact.recipient_key_index, expected["recipient_key_index"].getInt<uint32_t>());
        BOOST_CHECK_EQUAL(contact.account_reference, expected["account_reference"].getInt<uint32_t>());
        BOOST_CHECK_EQUAL(contact.created_at, expected["created_at"].getInt<uint64_t>());
        BOOST_CHECK_EQUAL(contact.core_height_created_at, expected["core_height_created_at"].getInt<uint32_t>());
        BOOST_CHECK_EQUAL(contact.encrypted_public_key.size(), 96U);
        BOOST_CHECK_EQUAL(contact.encrypted_account_label.size(), 48U);
    }
}

BOOST_AUTO_TEST_SUITE_END()
