// Copyright (c) 2026 The Dash Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

//! Tests for the Drive proved-response verification seam
//! (src/platform/drive/queries.*): synthesize the DAPI protobuf
//! request/response pairs the transport exchanges — grovedb proofs and the
//! quorum signature come from the JSON fixture corpus generated by the
//! platform-drive-vectors crate (github.com/PastaPastaPasta/dash-platform-test-vectors)
//! — push the fixture quorum key through the bridge, and verify end to end
//! (grovedb replay + Tenderdash BLS quorum signature inside
//! drive-proof-verifier).
//!
//! Every fixture proof commits to the same root hash and the fixture quorum
//! signed exactly that root, so the positive cases run the full pipeline.
//! The fixture grovedb state stores placeholder payloads at document
//! positions; the document-query case therefore pins a clean decode failure
//! (the upstream rs-drive-proof-verifier corpus pins the same). The
//! quorum-signature digest intermediates are covered upstream and no longer
//! re-derived here.

#include <test/data/platform/drive_query_vectors.json.h>
#include <test/data/platform/quorum_sig_vectors.json.h>

#include <platform/client.h>
#include <platform/drive/queries.h>
#include <platform/params.h>
#include <platform/transport/cbor.h>
#include <platform/transport/protobuf.h>
#include <platform/types.h>

#include <test/util/setup_common.h>
#include <util/strencodings.h>

#include <univalue.h>

#include <boost/test/unit_test.hpp>

#include <array>
#include <optional>
#include <string>
#include <vector>

using platform::Bytes;
using platform::Identifier;
using platform::ResponseMetadata;
using platform::drive::BridgeQuorumKey;
using platform::drive::ContestedVoteState;

BOOST_FIXTURE_TEST_SUITE(platform_drive_tests, BasicTestingSetup)

namespace {

UniValue ReadJsonObject(const unsigned char* data, size_t size)
{
    UniValue v;
    BOOST_REQUIRE(v.read(std::string(data, data + size)));
    BOOST_REQUIRE(v.isObject());
    return v;
}

Bytes FromHex(const std::string& hex)
{
    const auto parsed{TryParseHex<uint8_t>(hex)};
    BOOST_REQUIRE_MESSAGE(parsed.has_value(), "invalid hex in test vector: " + hex);
    return *parsed;
}

Identifier IdFromHex(const std::string& hex)
{
    const Bytes bytes{FromHex(hex)};
    BOOST_REQUIRE_EQUAL(bytes.size(), 32U);
    Identifier out{};
    std::copy(bytes.begin(), bytes.end(), out.begin());
    return out;
}

//! Returns the query object with the given name, or fails the test.
UniValue FindQuery(const UniValue& doc, const std::string& name)
{
    const UniValue& queries{doc["queries"]};
    for (size_t i = 0; i < queries.size(); ++i) {
        if (queries[i]["name"].get_str() == name) return queries[i];
    }
    BOOST_FAIL("query vector not found: " + name);
    return UniValue{};
}

Bytes ProofOf(const UniValue& query) { return FromHex(query["grovedb_proof_hex"].get_str()); }

//! The "valid" quorum-signature vector: envelope, block context and the
//! quorum public key that signed the root hash every drive query vector
//! commits to.
struct QuorumFixture {
    uint8_t quorum_type{0};
    Bytes quorum_hash;   //!< 32 bytes, DAPI proof (display) byte order
    Bytes block_id_hash; //!< 32 bytes
    int64_t round{0};
    Bytes signature; //!< 96 bytes
    Bytes pubkey;    //!< 48 bytes
    uint64_t height{0};
    uint32_t core_chain_locked_height{0};
    uint64_t time_ms{0};
    uint64_t protocol_version{0};
    std::string chain_id;
};

QuorumFixture LoadQuorumFixture()
{
    const UniValue doc{ReadJsonObject(json_tests::quorum_sig_vectors, sizeof(json_tests::quorum_sig_vectors))};
    const UniValue valid{doc["vectors"][0]};
    BOOST_REQUIRE_EQUAL(valid["name"].get_str(), "valid");
    QuorumFixture out;
    const UniValue& env{valid["envelope"]};
    out.quorum_type = static_cast<uint8_t>(env["quorum_type"].getInt<int>());
    out.quorum_hash = FromHex(env["quorum_hash"].get_str());
    out.block_id_hash = FromHex(env["block_id_hash"].get_str());
    out.round = env["round"].getInt<int>();
    out.signature = FromHex(env["signature"].get_str());
    out.pubkey = FromHex(valid["quorum_public_key"].get_str());
    const UniValue& ctx{valid["block_context"]};
    out.height = ctx["height"].getInt<int64_t>();
    out.core_chain_locked_height = static_cast<uint32_t>(ctx["core_chain_locked_height"].getInt<int64_t>());
    out.time_ms = ctx["time_ms"].getInt<int64_t>();
    out.protocol_version = ctx["protocol_version"].getInt<int64_t>();
    out.chain_id = ctx["chain_id"].get_str();
    return out;
}

//! Installs the fixture verification context in the bridge: the network the
//! fixture chain id belongs to plus the fixture quorum key. Idempotent, so
//! every test case simply calls it.
void SetupBridgeContext(const QuorumFixture& quorum)
{
    std::string err;
    BOOST_REQUIRE_MESSAGE(platform::drive::SetContext("test", /*platform_activation_height=*/0, err), err);
    BridgeQuorumKey key;
    BOOST_REQUIRE_EQUAL(quorum.quorum_hash.size(), key.proof_hash.size());
    std::copy(quorum.quorum_hash.begin(), quorum.quorum_hash.end(), key.proof_hash.begin());
    key.pubkey = quorum.pubkey;
    BOOST_REQUIRE_MESSAGE(platform::drive::UpdateQuorumKeys(quorum.quorum_type, {key}, err), err);
}

//! dapi-grpc Proof message binding `grovedb_proof` to the fixture-signed
//! block (platform.proto: grovedb_proof=1, quorum_hash=2, signature=3,
//! round=4, block_id_hash=5, quorum_type=6).
std::vector<uint8_t> EncodeProof(const QuorumFixture& quorum, const Bytes& grovedb_proof)
{
    platform::pb::Writer w;
    w.Bytes(1, grovedb_proof);
    w.Bytes(2, quorum.quorum_hash);
    w.Bytes(3, quorum.signature);
    w.Varint(4, static_cast<uint64_t>(quorum.round));
    w.Bytes(5, quorum.block_id_hash);
    w.Varint(6, quorum.quorum_type);
    return w.take();
}

//! dapi-grpc ResponseMetadata (height=1, core_chain_locked_height=2,
//! time_ms=4, protocol_version=5, chain_id=6).
std::vector<uint8_t> EncodeMetadata(const QuorumFixture& quorum)
{
    platform::pb::Writer w;
    w.Varint(1, quorum.height);
    w.Varint(2, quorum.core_chain_locked_height);
    w.Varint(4, quorum.time_ms);
    w.Varint(5, quorum.protocol_version);
    w.Str(6, quorum.chain_id);
    return w.take();
}

//! Every proved Get*Response shares the v0 shape {result.proof=2,
//! metadata=3} wrapped in a version oneof (field 1).
std::vector<uint8_t> WrapResponse(std::vector<uint8_t> proof_msg, std::vector<uint8_t> metadata_msg)
{
    platform::pb::Writer v0;
    v0.Message(2, proof_msg);
    v0.Message(3, metadata_msg);
    platform::pb::Writer outer;
    outer.Message(1, v0.take());
    return outer.take();
}

std::vector<uint8_t> WrapRequest(platform::pb::Writer v0)
{
    platform::pb::Writer outer;
    outer.Message(1, v0.take());
    return outer.take();
}

//! Request encodings mirroring src/platform/transport/client.cpp.
std::vector<uint8_t> NonceRequest(const Identifier& id)
{
    platform::pb::Writer v0;
    v0.Bytes(1, std::vector<uint8_t>(id.begin(), id.end()));
    v0.Bool(2, true);
    return WrapRequest(std::move(v0));
}

std::vector<uint8_t> ContractNonceRequest(const Identifier& id, const Identifier& contract)
{
    platform::pb::Writer v0;
    v0.Bytes(1, std::vector<uint8_t>(id.begin(), id.end()));
    v0.Bytes(2, std::vector<uint8_t>(contract.begin(), contract.end()));
    v0.Bool(3, true);
    return WrapRequest(std::move(v0));
}

//! drive-abci decodes each contested index value as a bincode (standard)
//! platform Value; strings are discriminant 18 + length + utf8.
std::vector<uint8_t> BincodeTextValue(const std::string& text)
{
    std::vector<uint8_t> out;
    out.push_back(18);
    BOOST_REQUIRE(text.size() < 251);
    out.push_back(static_cast<uint8_t>(text.size()));
    out.insert(out.end(), text.begin(), text.end());
    return out;
}

std::vector<uint8_t> ContestedRequest(const std::string& normalized_label, uint64_t count)
{
    platform::pb::Writer v0;
    v0.Bytes(1, std::vector<uint8_t>(platform::DPNS_CONTRACT_ID.begin(), platform::DPNS_CONTRACT_ID.end()));
    v0.Str(2, "domain");
    v0.Str(3, "parentNameAndLabel");
    v0.Bytes(4, BincodeTextValue("dash"));
    v0.Bytes(4, BincodeTextValue(normalized_label));
    v0.Varint(5, 1);  // ResultType::VOTE_TALLY
    v0.Bool(6, true); // allow_include_locked_and_abstaining_vote_tally
    v0.Varint(8, count);
    v0.Bool(9, true); // prove
    return WrapRequest(std::move(v0));
}

std::vector<uint8_t> DpnsExactRequest(const std::string& normalized_label)
{
    platform::transport::cbor::Writer where;
    where.Array(2);
    where.Array(3); where.Text("normalizedParentDomainName"); where.Text("=="); where.Text("dash");
    where.Array(3); where.Text("normalizedLabel"); where.Text("=="); where.Text(normalized_label);
    platform::pb::Writer v0;
    v0.Bytes(1, std::vector<uint8_t>(platform::DPNS_CONTRACT_ID.begin(), platform::DPNS_CONTRACT_ID.end()));
    v0.Str(2, "domain");
    v0.Bytes(3, where.take());
    v0.Varint(5, 1); // limit
    v0.Bool(8, true); // prove
    return WrapRequest(std::move(v0));
}

void CheckMeta(const ResponseMetadata& meta, const QuorumFixture& quorum)
{
    BOOST_CHECK_EQUAL(meta.height, quorum.height);
    BOOST_CHECK_EQUAL(meta.core_chain_locked_height, quorum.core_chain_locked_height);
    BOOST_CHECK_EQUAL(meta.time_ms, quorum.time_ms);
    BOOST_CHECK_EQUAL(meta.protocol_version, quorum.protocol_version);
    BOOST_CHECK_EQUAL(meta.chain_id, quorum.chain_id);
}

} // namespace

// ---------------------------------------------------------------------------
// Positive end-to-end verification (grovedb replay + quorum signature)
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(identity_nonce_end_to_end)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const QuorumFixture quorum{LoadQuorumFixture()};
    SetupBridgeContext(quorum);
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};

    {
        const UniValue q{FindQuery(doc, "identity_nonce")};
        const auto request{NonceRequest(id)};
        const auto response{WrapResponse(EncodeProof(quorum, ProofOf(q)), EncodeMetadata(quorum))};
        std::optional<uint64_t> nonce;
        ResponseMetadata meta;
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyGetIdentityNonce(request, response, nonce, meta, error), error);
        BOOST_REQUIRE(nonce.has_value());
        BOOST_CHECK_EQUAL(*nonce, q["expected"]["nonce"].getInt<uint64_t>());
        CheckMeta(meta, quorum);
    }
    {
        const UniValue q{FindQuery(doc, "identity_contract_nonce")};
        const Identifier contract{IdFromHex(q["query"]["contract_id"].get_str())};
        const auto request{ContractNonceRequest(id, contract)};
        const auto response{WrapResponse(EncodeProof(quorum, ProofOf(q)), EncodeMetadata(quorum))};
        std::optional<uint64_t> nonce;
        ResponseMetadata meta;
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyGetIdentityContractNonce(request, response, nonce, meta, error),
            error);
        BOOST_REQUIRE(nonce.has_value());
        BOOST_CHECK_EQUAL(*nonce, q["expected"]["nonce"].getInt<uint64_t>());
        CheckMeta(meta, quorum);
    }
}

BOOST_AUTO_TEST_CASE(contested_vote_state_end_to_end)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const QuorumFixture quorum{LoadQuorumFixture()};
    SetupBridgeContext(quorum);
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    const Identifier contender_b{IdFromHex(std::string(64, '8'))};

    const auto verify = [&](const std::string& name, ContestedVoteState& state) {
        const UniValue q{FindQuery(doc, name)};
        const auto request{ContestedRequest(q["query"]["normalized_label"].get_str(),
                                            q["query"]["count"].getInt<uint64_t>())};
        const auto response{WrapResponse(EncodeProof(quorum, ProofOf(q)), EncodeMetadata(quorum))};
        ResponseMetadata meta;
        std::string error;
        BOOST_REQUIRE_MESSAGE(
            platform::drive::VerifyGetContestedVoteState(request, response, state, meta, error),
            name + ": " + error);
        CheckMeta(meta, quorum);
        return q;
    };

    // Active poll: live tallies from the contender/abstain/lock sum trees;
    // the Started stored-info item is ignored.
    {
        ContestedVoteState state;
        verify("contested_vote_state_active", state);
        BOOST_CHECK(state.contest_found);
        BOOST_CHECK(!state.finished);
        BOOST_REQUIRE_EQUAL(state.contenders.size(), 2U);
        BOOST_CHECK(state.contenders[0].first == id);
        BOOST_CHECK_EQUAL(state.contenders[0].second, 5U);
        BOOST_CHECK(state.contenders[1].first == contender_b);
        BOOST_CHECK_EQUAL(state.contenders[1].second, 2U);
        BOOST_CHECK(state.abstain_votes == std::optional<uint32_t>{2});
        BOOST_CHECK(state.lock_votes == std::optional<uint32_t>{3});
        BOOST_CHECK(!state.winner.has_value());
    }

    // Finished poll: outcome comes from the awarded stored info.
    {
        ContestedVoteState state;
        verify("contested_vote_state_finished", state);
        BOOST_CHECK(state.contest_found);
        BOOST_CHECK(state.finished);
        BOOST_CHECK(!state.locked);
        BOOST_REQUIRE(state.winner.has_value());
        BOOST_CHECK(*state.winner == id);
        BOOST_REQUIRE_EQUAL(state.contenders.size(), 2U);
        BOOST_CHECK_EQUAL(state.contenders[0].second, 5U);
        BOOST_CHECK_EQUAL(state.contenders[1].second, 2U);
        BOOST_CHECK(state.abstain_votes == std::optional<uint32_t>{2});
        BOOST_CHECK(state.lock_votes == std::optional<uint32_t>{1});
        BOOST_CHECK(state.finished_at_time_ms > 0);
    }

    // Absent contest: cryptographically proven "no contest for this label".
    {
        ContestedVoteState state;
        verify("contested_vote_state_absent", state);
        BOOST_CHECK(!state.contest_found);
        BOOST_CHECK(state.contenders.empty());
    }
}

// ---------------------------------------------------------------------------
// Document queries: the fixture stores placeholder payloads at document
// positions, so grovedb + query-shape verification succeeds and the DPP
// document decode must fail cleanly (an error, never a crash). Positive
// document decoding is covered by the upstream corpus and the dpp decoder
// tests (platform_dpp_tests) on real serialized documents.
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(placeholder_documents_fail_decoding_cleanly)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const QuorumFixture quorum{LoadQuorumFixture()};
    SetupBridgeContext(quorum);

    const UniValue q{FindQuery(doc, "dpns_exact")};
    const auto request{DpnsExactRequest("alice")};
    const auto response{WrapResponse(EncodeProof(quorum, ProofOf(q)), EncodeMetadata(quorum))};
    std::vector<Bytes> documents;
    ResponseMetadata meta;
    std::string error;
    BOOST_CHECK(!platform::drive::VerifyGetDocuments(request, response, documents, meta, error));
    BOOST_CHECK(!error.empty());
    // The failure must come from the DPP decode, not from the grovedb
    // replay: a query-shape drift would surface as a "grovedb:" proof error.
    BOOST_CHECK_MESSAGE(error.find("grovedb") == std::string::npos, error);
    BOOST_CHECK(documents.empty());
}

// ---------------------------------------------------------------------------
// Negative cases: quorum binding
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(tampered_responses_are_rejected)
{
    const UniValue doc{ReadJsonObject(json_tests::drive_query_vectors, sizeof(json_tests::drive_query_vectors))};
    const QuorumFixture quorum{LoadQuorumFixture()};
    SetupBridgeContext(quorum);
    const Identifier id{IdFromHex(doc["identity_id"].get_str())};
    const UniValue q{FindQuery(doc, "identity_nonce")};
    const auto request{NonceRequest(id)};

    const auto reject = [&](const std::vector<uint8_t>& response, const std::string& what) {
        std::optional<uint64_t> nonce;
        ResponseMetadata meta;
        std::string error;
        BOOST_CHECK_MESSAGE(
            !platform::drive::VerifyGetIdentityNonce(request, response, nonce, meta, error), what);
        BOOST_CHECK_MESSAGE(!error.empty(), what);
    };

    // Tampered quorum signature.
    {
        QuorumFixture bad{quorum};
        bad.signature[10] ^= 0x01;
        reject(WrapResponse(EncodeProof(bad, ProofOf(q)), EncodeMetadata(quorum)),
               "tampered signature must fail");
    }
    // Unknown quorum: the bridge has no key for the flipped hash.
    {
        QuorumFixture bad{quorum};
        bad.quorum_hash[0] ^= 0x01;
        reject(WrapResponse(EncodeProof(bad, ProofOf(q)), EncodeMetadata(quorum)),
               "unknown quorum must fail");
    }
    // Tampered grovedb proof: the recomputed root no longer matches the
    // signed app hash (or the proof fails to replay at all).
    {
        Bytes proof{ProofOf(q)};
        proof[proof.size() / 2] ^= 0x01;
        reject(WrapResponse(EncodeProof(quorum, proof), EncodeMetadata(quorum)),
               "tampered grovedb proof must fail");
    }
    // Tampered signed metadata: the height enters the StateId sign bytes.
    {
        QuorumFixture bad{quorum};
        ++bad.height;
        reject(WrapResponse(EncodeProof(quorum, ProofOf(q)), EncodeMetadata(bad)),
               "tampered signed height must fail");
    }
}

// The client feeds quorum keys to the bridge in DAPI (display) byte order;
// QuorumKey::matchesProofHash documents that representation boundary against
// Dash Core's internal little-endian uint256.
BOOST_AUTO_TEST_CASE(quorum_key_matches_dapi_hash_byte_order)
{
    platform::QuorumKey key;
    for (size_t i = 0; i < key.quorum_hash.size(); ++i) {
        key.quorum_hash.begin()[i] = static_cast<uint8_t>(i);
    }

    std::array<uint8_t, 32> proof_hash{};
    for (size_t i = 0; i < proof_hash.size(); ++i) {
        proof_hash[i] = static_cast<uint8_t>(proof_hash.size() - 1 - i);
    }
    BOOST_CHECK(key.matchesProofHash(proof_hash));

    proof_hash[0] ^= 1;
    BOOST_CHECK(!key.matchesProofHash(proof_hash));
}

BOOST_AUTO_TEST_SUITE_END()
