.TH KLIQ-CLI "1" "June 2016" "kliq-cli 0.12"
.SH NAME
kliq-cli \- a remote procedure call client for Kliq Core. 
.SH SYNOPSIS
kliq-cli [options] <command> [params] \- Send command to Kliq Core. 
.TP
kliq-cli [options] help \- Asks Kliq Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the kliq-cli program. kliq-cli is an RPC client used to send commands to Kliq Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBkliqd\fP, \fBkliq.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
