.TH KRISS-CLI "1" "June 2016" "kriss-cli 0.12"
.SH NAME
kriss-cli \- a remote procedure call client for Kriss Core. 
.SH SYNOPSIS
kriss-cli [options] <command> [params] \- Send command to Kriss Core. 
.TP
kriss-cli [options] help \- Asks Kriss Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the kriss-cli program. kriss-cli is an RPC client used to send commands to Kriss Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBkrissd\fP, \fBkriss.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
