name: CI

on:
  push:
  pull_request_target:

permissions:
  contents: read
  packages: write

concurrency:
  group: |
    ${{ github.workflow }}-${{
      (vars.ALLOW_CONCURRENCY != '' && github.sha) ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.number) ||
      (github.event_name == 'push' && github.ref)
    }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  container:
    name: Build containers (amd64)
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./contrib/containers/ci
      file: ./contrib/containers/ci/ci.Dockerfile
      name: dashcore-ci-runner
      slim-file: ./contrib/containers/ci/ci-slim.Dockerfile
      slim-name: dashcore-ci-slim

  container-arm64:
    name: Build containers (ARM64)
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./contrib/containers/ci
      file: ./contrib/containers/ci/ci.Dockerfile
      name: dashcore-ci-runner
      slim-file: ./contrib/containers/ci/ci-slim.Dockerfile
      slim-name: dashcore-ci-slim
      runs-on: ubuntu-24.04-arm

  depends-arm-linux:
    name: arm-linux-gnueabihf
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: ${{ vars.SKIP_ARM_LINUX == '' }}
    with:
      build-target: arm-linux
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64:
    name: x86_64-pc-linux-gnu
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: |
      vars.SKIP_LINUX64 == '' ||
      vars.SKIP_LINUX64_FUZZ == '' ||
      vars.SKIP_LINUX64_SQLITE == '' ||
      vars.SKIP_LINUX64_UBSAN == ''
    with:
      build-target: linux64
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64_multiprocess:
    name: x86_64-pc-linux-gnu_multiprocess
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: |
      vars.SKIP_LINUX64_MULTIPROCESS == '' ||
      vars.SKIP_LINUX64_TSAN == ''
    with:
      build-target: linux64_multiprocess
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64_nowallet:
    name: x86_64-pc-linux-gnu_nowallet
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: ${{ vars.SKIP_LINUX64_NOWALLET == '' }}
    with:
      build-target: linux64_nowallet
      container-path: ${{ needs.container.outputs.path }}

  depends-mac:
    name: x86_64-apple-darwin
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: ${{ vars.SKIP_MAC == '' }}
    with:
      build-target: mac
      container-path: ${{ needs.container.outputs.path }}

  depends-win64:
    name: x86_64-w64-mingw32
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    if: ${{ vars.SKIP_WIN64 == '' }}
    with:
      build-target: win64
      container-path: ${{ needs.container.outputs.path }}

  src-arm-linux:
    name: arm-linux-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-arm-linux]
    with:
      build-target: arm-linux
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-arm-linux.outputs.key }}

  src-linux64:
    name: linux64-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    if: ${{ vars.SKIP_LINUX64 == '' }}
    with:
      build-target: linux64
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_fuzz:
    name: linux64_fuzz-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    if: ${{ vars.SKIP_LINUX64_FUZZ == '' }}
    with:
      build-target: linux64_fuzz
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_multiprocess:
    name: linux64_multiprocess-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64_multiprocess]
    if: ${{ vars.SKIP_LINUX64_MULTIPROCESS == '' }}
    with:
      build-target: linux64_multiprocess
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64_multiprocess.outputs.key }}

  src-linux64_nowallet:
    name: linux64_nowallet-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64_nowallet]
    with:
      build-target: linux64_nowallet
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64_nowallet.outputs.key }}

  src-linux64_sqlite:
    name: linux64_sqlite-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    if: ${{ vars.SKIP_LINUX64_SQLITE == '' }}
    with:
      build-target: linux64_sqlite
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_tsan:
    name: linux64_tsan-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64_multiprocess]
    if: ${{ vars.SKIP_LINUX64_TSAN == '' }}
    with:
      build-target: linux64_tsan
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64_multiprocess.outputs.key }}

  src-linux64_ubsan:
    name: linux64_ubsan-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    if: ${{ vars.SKIP_LINUX64_UBSAN == '' }}
    with:
      build-target: linux64_ubsan
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-mac:
    name: mac-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-mac]
    with:
      build-target: mac
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-mac.outputs.key }}

  src-win64:
    name: win64-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-win64]
    with:
      build-target: win64
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-win64.outputs.key }}

  test-linux64:
    name: linux64-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64]
    with:
      bundle-key: ${{ needs.src-linux64.outputs.key }}
      build-target: linux64
      container-path: ${{ needs.container.outputs.slim-path }}

  test-linux64_multiprocess:
    name: linux64_multiprocess-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64_multiprocess]
    with:
      bundle-key: ${{ needs.src-linux64_multiprocess.outputs.key }}
      build-target: linux64_multiprocess
      container-path: ${{ needs.container.outputs.slim-path }}

  test-linux64_nowallet:
    name: linux64_nowallet-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64_nowallet]
    with:
      bundle-key: ${{ needs.src-linux64_nowallet.outputs.key }}
      build-target: linux64_nowallet
      container-path: ${{ needs.container.outputs.slim-path }}

  test-linux64_sqlite:
    name: linux64_sqlite-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64_sqlite]
    with:
      bundle-key: ${{ needs.src-linux64_sqlite.outputs.key }}
      build-target: linux64_sqlite
      container-path: ${{ needs.container.outputs.slim-path }}

  test-linux64_tsan:
    name: linux64_tsan-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64_tsan]
    with:
      bundle-key: ${{ needs.src-linux64_tsan.outputs.key }}
      build-target: linux64_tsan
      container-path: ${{ needs.container.outputs.slim-path }}

  test-linux64_ubsan:
    name: linux64_ubsan-test
    uses: ./.github/workflows/test-src.yml
    needs: [container, src-linux64_ubsan]
    with:
      bundle-key: ${{ needs.src-linux64_ubsan.outputs.key }}
      build-target: linux64_ubsan
      container-path: ${{ needs.container.outputs.slim-path }}

  test-arm-linux:
    name: arm-linux-test
    uses: ./.github/workflows/test-src.yml
    needs: [container-arm64, src-arm-linux]
    with:
      bundle-key: ${{ needs.src-arm-linux.outputs.key }}
      build-target: arm-linux
      container-path: ${{ needs.container-arm64.outputs.slim-path }}
